name: Build C++ part on Ubuntu 24.04

on:
  pull_request:
    branches:
      - master
  push:
    branches:
      - master
    paths-ignore:
      - '.github/workflows/**'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-24.04
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Update package list
        run:  sudo apt-get update
      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y cmake g++ git wget unzip

      - name: Cache libtorch
        uses: actions/cache@v4
        with:
          path: /opt/libtorch
          key: libtorch-2.8.0
          restore-keys: |
            libtorch-

      - name: Download and extract libtorch
        run: |
          if [ -d /opt/libtorch/ ] ; then
              echo "Using cached libtorch"
              ls -alh /opt/libtorch/
          else
              wget -q https://download.pytorch.org/libtorch/cpu/libtorch-shared-with-deps-2.8.0%2Bcpu.zip -O /tmp/libtorch.zip
              unzip -q /tmp/libtorch.zip -d /opt/
              rm /tmp/libtorch.zip
          fi

      - name: Clone libosmscout repository
        run: |
          git clone --depth 1 https://github.com/Framstag/libosmscout.git

      - name: Cache libosmscout build
        uses: actions/cache@v4
        with:
          path: /opt/libosmscout/
          key: libosmscout-build-${{ hashFiles('libosmscout/**') }}
          restore-keys: |
            libosmscout-build-

      - name: Build and install libosmscout
        run: |          
          if [ -d /opt/libosmscout/ ] ; then
            echo "Using cached libosmscout build"
            ls -alh /opt/libosmscout/include
          else
            mkdir -p libosmscout-build && cd libosmscout-build
            cmake ../libosmscout -DCMAKE_BUILD_TYPE=Release -DCMAKE_INSTALL_PREFIX=/opt/libosmscout/
            sudo cmake --build . --target install -- -j$(nproc)
            cd ..
          fi

      - name: Configure CMake
        run: cmake -S . -B build

      - name: Build
        run: cmake --build build -DCMAKE_PREFIX_PATH=/opt/libtorch/ -- -j$(nproc)
