name: Ubuntu 24.04

on:
  pull_request:
    branches:
      - master
  push:
    branches:
      - master
    paths-ignore:
      - '.github/workflows/**'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-24.04
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Update package list
        run:  sudo apt-get update
      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y cmake g++ git

      - name: Clone libosmscout repository
        run: |
          git clone --depth 1 https://github.com/Framstag/libosmscout.git

      - name: Cache libosmscout build
        uses: actions/cache@v4
        with:
          path: /opt/libosmscout/
          key: libosmscout-build-${{ hashFiles('libosmscout/**') }}
          restore-keys: |
            libosmscout-build-

      - name: Build and install libosmscout
        run: |
          ls -alh /opt/libosmscout/include
          if [ ! -d /opt/libosmscout/ ] ; then
            mkdir -p libosmscout-build && cd libosmscout-build
            cmake ../libosmscout -DCMAKE_BUILD_TYPE=Release -DCMAKE_INSTALL_PREFIX=/opt/libosmscout/
            sudo cmake --build . --target install
            cd ..
          fi

      - name: Configure CMake
        run: cmake -S . -B build

      - name: Build
        run: cmake --build build
